version: "3.3"
services:
  app:
    stop_signal: SIGTERM
    stop_grace_period: 30s
    ports:
      - '8080:8080'
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - app.env
